/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/RequestConfig.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

export {RequestConfig};

declare namespace UiElements {

  /**
   * A per-request configuration oprions.
   */
  class RequestConfig extends LitElement {

    /**
     * Request configuration object
     */
    config: object|null|undefined;

    /**
     * Enables compatibility with Anypoint platform
     */
    compatibility: boolean|null|undefined;

    /**
     * Enables material's outlined theme for inputs.
     */
    outlined: boolean|null|undefined;

    /**
     * When set the editor is in read only mode.
     */
    readOnly: boolean|null|undefined;
    constructor();
    render(): any;
    _setDefaults(): void;
    _inputHandler(e: any): void;
    _checkedHandler(e: any): void;
    notify(): void;
    _headerTemplate(configEnabled: any, compatibility: any, readOnly: any): any;
    _redirectsTemplate(enabled: any, config: any, compatibility: any, readOnly: any): any;
    _timeoutTemplate(enabled: any, config: any, compatibility: any, outlined: any, readOnly: any): any;
    _validateSslTemplate(enabled: any, config: any, compatibility: any, readOnly: any): any;
    _nodeClientTemplate(enabled: any, config: any, compatibility: any, readOnly: any): any;
    _defaultHeadersTemplate(enabled: any, config: any, compatibility: any, readOnly: any): any;
  }
}
